version: 0.1

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo nothing to do know
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*
