version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.9
jobs:
  deploy_code_react_to_cloud_front:
      working_directory: ~/app
      docker:
          - image: circleci/node:8.11.0
      steps:
          - checkout
          - run:
              name: Clone React Repo
              command: |
                git clone https://github.com/btrettin/my-portfolio
          - run:
              name: update-npm
              command: 'sudo npm install -g npm@latest'
          - run:
              name: Install Dependencies
              command: |
                cd my-portfolio
                npm install --only=dev
                npm install
          - run:
              name: Added domainRequests.json
              command: |
                touch ./my-portfolio/src/domainRequests.json
                echo "{}" >> ./my-portfolio/src/domainRequests.json
          - run:
              name: Unit Tests For React
              command: |
                cd my-portfolio && npm run test
          - run:
              name: Build React
              command: |
                cd my-portfolio && npm run build
          - run:
              name: Install AWS CLI
              command: |
                sudo apt-get -y -qq install awscli
          - run:
              name: Configure AWS CLI to Run as Admin
              command: |
                  aws configure set aws_access_key_id $adminAccessKey
                  aws configure set aws_secret_access_key $adminSecretAccessKey
                  aws configure set default.region $REGION
          - run:
              name: Ship Build File To S3 Bucket
              command: |
                 aws configure set aws_access_key_id $adminAccessKey
                 aws configure set aws_secret_access_key $adminSecretAccessKey
                 aws configure set default.region $REGION
                 cd my-portfolio
                 echo $FrontendDeploymentBucket
                 aws s3 mv ./build s3://${FrontendDeploymentBucket} --recursive --acl public-read-write
workflows:
    version: 2
    build_and_test:
        jobs:
            - deploy_code_react_to_cloud_front:
